name: Build GTS Apps version3 (Windows)

on:
  workflow_dispatch:
  push:
    paths:
      - "GTS_Summary.py"
      - "GTS_LG_GUI.py"
      - ".github/workflows/build_workflow.yml"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install pyinstaller customtkinter cryptography pillow

      - name: Build GTS_Summary (Windows)
        run: |
          pyinstaller --noconfirm --onefile --windowed --name GTS_Summary GTS_Summary.py --icon=SED_ICON.ico --add-data "SED_ICON.jpg;."

      - name: Build GTS_LG (Windows)
        run: |
          pyinstaller --noconfirm --onefile --windowed --name GTS_LG GTS_LG_GUI.py --icon=SED_ICON.ico

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GTS_Apps_Windows
          path: |
            dist/GTS_Summary.exe
            dist/GTS_LG.exe
